server {
    listen 5173;

    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        try_files $uri $uri/ /index.html;
    }

    # Optional: Proxy to the Spring Boot backend
    # location /api/ {
    #     proxy_pass http://springboot-app:8080;
    # }
}
